--- #YAML:1.0
name:               ZCS-LocalConfig
version:            1.00
abstract:           Perl module for the Zimbra Collaboration Suite
author:
    - Phil Pearl <phil@zimbra.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    XML::Parser:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
